# Mapping
resolution : 0.05
apply_filter : False
add_max_ranges : False
add_rays : False
map_frame : "map"
fixed_frame : "odom"
robot_frame : "base_link"
offline_octomap_path : ""
#offline_octomap_path : "/home/dev/map_laser_octomap.bt"
visualize_free_space : False
projection_2d : False
odometry_topic : "/odometry/filtered"

minimum_range : 0.1 # -1 if no filtering is required
rviz_timer : 1.0 # 0.0 if no visualization

laser_scan_topics : ["/base_scan"]
laser_scan_frames : ["/laser_link"] 

point_cloud_topics : ["/head_camera/depth_downsample/points"]
point_cloud_frames : ["/head_camera_rgb_optical_frame"]
