# Mapping
resolution: 0.05
apply_filter: False
add_max_ranges: False
add_rays: False
map_frame: "map"
fixed_frame: "odom"
robot_frame: "base_link"
# offline_octomap_path: ""
offline_octomap_path: "/home/sasm/ros/melodic/system/src/real_pepper_pipeline/map/robot_lab.bt"
visualize_free_space: False
projection_2d: True
odometry_topic: "/pepper_robot/odom"

minimum_range: 0.1 # -1 if no filtering is required
rviz_timer: 1.0 # 0.0 if no visualization

# laser_scan_topics: ["/pepper/laser_2"]
# laser_scan_frames: ["/SurroundingFrontLaser_fake_hokuyo_frame"]

# point_cloud_topics: ["/pepper/camera/depth/points"]
# point_cloud_frames: ["/CameraDepth_frame"]

# social agents config
social_agents_config: "/pedsim_simulator/simulated_agents"
