###### topics and services ######

## input topics
topic_in_cloud: "/pepper/camera/depth/points"
topic_in_cloud_old: ""
topic_in_laser: ""

## output topics
topic_out_cloud: "/pepper/camera/depth/points_filtered"

###### general settings ######

## input filtering
#skip_count        :    0 # skip no pointcouds
#skip_time         : 0.2  # skip all pointclouds within 0.2 seconds
#enabled           : true # node starts active

## tf
#tf_lookup_time    : 0.2  # waiting up to 0.2 seconds

## buffering
buffer_pointcloud: true # save last pointcloud

## extended output for debugging
#debugging         : false # normal output

###### laser ######

## all nans within laserscan will be replaced by this range value
##   if < 0 then this feature will deactivated
#laser_nan_replacement_value: -1 # meter

###### filter ######

filters:
  [
    "cylinder: 2 2 agent_1 #agent_1",
    "cylinder: 2 2 agent_2 #agent_2",
    "cylinder: 2 2 agent_3 #agent_3",
    "cylinder: 2 2 agent_4 #agent_4",
    "cylinder: 2 2 agent_5 #agent_5",
    "cylinder: 2 2 agent_6 #agent_6",
    "cylinder: 2 2 agent_7 #agent_7",
    "cylinder: 2 2 agent_8 #agent_8",
    "cylinder: 2 2 agent_9 #agent_9",
    "cylinder: 2 2 agent_10 #agent_10",
  ]
