# Path planning parameters
world_frame: odom
planner_name: RRTstar # RRT, RRTstar
planning_bounds_x: [-50.0, 50.0] # [x_min, x_max]
planning_bounds_y: [-50.0, 50.0] # [y_min, y_max]
dynamic_bounds: True # the bounds of the planner will change according to the start and goal configurations
start_state: [15.0, 0.0, 0.0] # [X, Y, Yaw]
goal_state: [25.0, 0.0, 0.0] # [X, Y, Yaw]
timer_period: 1.0
solving_time: 0.9
opport_collision_check: True
reuse_last_best_solution: True
optimization_objective: RiskZones #PathLength, RiskZones
motion_cost_interpolation: False
start_prev_path_proj: False
xy_goal_tolerance: 0.25
visualize_tree: False

# Collision checking
octomap_service: /fetch_move_base_mapper/get_binary
global_map_topic: /map
fetch_base_height: 0.4
fetch_base_radius: 0.33

odometry_topic: /odometry/filtered
query_goal_topic: /fetch_move_base_planner/query_goal
solution_path_topic: /fetch_move_base_planner/solution_path
