# Control parameters
max_vel : 0.15
min_vel : 0.05
xy_goal_tolerance : 0.2
yaw_goal_tolerance : 0.2
controller_hz : 100.0
control_path_topic : /fetch_move_base_planner/fetch_move_base_solution_path
control_output_topic : /cmd_vel
odometry_topic : /odometry/filtered
